import {
  algorithmAnalysisAndDesign,
  electron,
  grpc,
  iotJs,
  memoryJs,
  memoryLeaksJs,
  p2p,
  protobuf,
  reactNative,
  v8,
  webRTC,
  softwareArchitecture,
  microservicesArchitecture,
  nodejsNativeCppModules,
  libuvAndAsynchronousIO,
  webAssembly,
  kafka,
  rabbitMQ,
  elasticSearch,
  aws,
} from '../../tags';

export default [
  algorithmAnalysisAndDesign,
  softwareArchitecture,
  microservicesArchitecture,
  memoryJs,
  memoryLeaksJs,
  v8,
  nodejsNativeCppModules,
  libuvAndAsynchronousIO,
  protobuf,
  grpc,
  p2p,
  webRTC,
  iotJs,
  webAssembly,
  kafka,
  rabbitMQ,
  elasticSearch,
  reactNative,
  electron,
  aws,
];
