import {
  algorithmAnalysisAndDesign,
  electron,
  grpc,
  nodejsIoT,
  memoryJs,
  memoryLeaksJs,
  p2p,
  protobuf,
  reactNative,
  enginesJs,
  webRTC,
  softwareArchitecture,
  microservicesArchitecture,
  nodejsNativeCppModules,
  libuvAsynchronousIO,
  webAssembly,
  kafka,
  rabbitMQ,
  aws,
} from '../../tags';

export default [
  algorithmAnalysisAndDesign,
  softwareArchitecture,
  microservicesArchitecture,
  memoryJs,
  memoryLeaksJs,
  enginesJs,
  nodejsNativeCppModules,
  libuvAsynchronousIO,
  protobuf,
  grpc,
  p2p,
  webRTC,
  nodejsIoT,
  webAssembly,
  kafka,
  rabbitMQ,
  reactNative,
  electron,
  aws,
];
