import {
  algorithmAnalysisAndDesign,
  databasesAdvanced,
  dataStructuresRealisation,
  electron,
  grpc,
  nodejsIoT,
  linuxAdvanced,
  memoryJs,
  memoryLeaksJs,
  networkAdvanced,
  p2p,
  protobuf,
  reactNative,
  enginesJs,
  webGL,
  webRTC,
} from '../../tags';

export default [
  algorithmAnalysisAndDesign,
  dataStructuresRealisation,
  memoryJs,
  memoryLeaksJs,
  webGL,
  enginesJs,
  protobuf,
  grpc,
  p2p,
  webRTC,
  nodejsIoT,
  linuxAdvanced,
  networkAdvanced,
  databasesAdvanced,
  reactNative,
  electron,
];
